### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference & SIGSEGV

### ISSUE THREAD

**Issue by ThomasG77** [xwjdsh/manssh#5]
## Configuration

**OS:** Ubuntu 16.04
**go version:** go1.10.2 linux/amd64

## Process I've done

Then I do an install with
```
go get -u github.com/xwjdsh/manssh/cmd/manssh
```
and run the following
```
manssh list
```
It returns this error trace

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x52c814]

goroutine 1 [running]:
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.decode.func1(0xc4200616e8)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/config.go:216 +0x1f2
panic(0x579640, 0x68f8d0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.(*sshParser).parseKV(0xc4200be1e0, 0xc42009ff20)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/parser.go:99 +0x264
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.(*sshParser).(github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.parseKV)-fm(0xc42009ff20)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/parser.go:80 +0x2a
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.(*sshParser).run(0xc4200be1e0)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/parser.go:38 +0x42
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.parseSSH(0xc420094180, 0xc4200b0000, 0xc420094180)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/parser.go:180 +0x307
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.decode(0x5c7680, 0xc4200b8048, 0x0, 0x0, 0x0, 0x0)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/config.go:226 +0x90
github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config.Decode(0x5c7680, 0xc4200b8048, 0x440, 0x180, 0xc4200b8048)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/xwjdsh/ssh_config/config.go:209 +0x3c
github.com/xwjdsh/manssh.ParseConfig(0xc4200b6e20, 0x19, 0x0, 0x0)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/sshconfig.go:26 +0x78
github.com/xwjdsh/manssh.List(0xc4200b6e20, 0x19, 0x6b3800, 0x0, 0x0, 0xc420061a77, 0x1, 0x1, 0x5, 0x4, ...)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/sshconfig.go:38 +0x6e
main.list(0xc4200c42c0, 0x0, 0xc4200c42c0)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/cmd/manssh/actions.go:17 +0xe1
github.com/xwjdsh/manssh/vendor/github.com/urfave/cli.HandleAction(0x570100, 0x5b1a18, 0xc4200c42c0, 0xc4200be100, 0x0)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/xwjdsh/manssh/vendor/github.com/urfave/cli.Command.Run(0x5a69d0, 0x4, 0x0, 0x0, 0xc42009e470, 0x1, 0x1, 0x5ac7f3, 0x1f, 0x0, ...)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/xwjdsh/manssh/vendor/github.com/urfave/cli.(*App).Run(0xc4200c04e0, 0xc4200aa020, 0x2, 0x2, 0x0, 0x0)
	/home/thomasg/go/src/github.com/xwjdsh/manssh/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/home/thomasg/go/src/github.com/xwjdsh/manssh/cmd/manssh/main.go:21 +0x11c
```
I also tried directly with the release file `manssh_0.4.0_linux_amd64.tar.gz` from https://github.com/xwjdsh/manssh/releases

**Comment by xwjdsh** [comment]
The error occurred when parsing the ssh configuration file, you can debug locally (comment out some of the aliases, then run `manssh list`), you will find the configuration that causes the panic error.

I use the [kevinburke/ssh_config](https://github.com/kevinburke/ssh_config) package to parse ssh configuration, I will submit a PR, output more log to help locate the problem.

**Comment by ThomasG77** [comment]
Thanks! The issue was due to a different number of spaces in one of the config `Host` block.
